production:
  url: <%= ENV['DATABASE_URL'] %>
  # host: student-knowledge-system.herokuapp.com

development:
  adapter: postgresql # should be sqlite3, but get foreign key error, will fix in next iteration
  encoding: unicode
  database: courses
  username: postgres
  password: 1234
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: courses
  username: postgres
  password: 1234
  host: localhost
  pool: 5
